config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "customers#index"

  resources :customers do
    collection do
      get 'alphabetized'
    end

    collection do
      get 'missing_email'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :email, presence: false
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order('fullname ASC')
  end

  def missing_email
    @customers = Customer.where(email: [nil,''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="c">
  <div class = "b">
  <div style="background-color: #f2f2f2">
      <p class="title">
          <%= customer.fullname %>
      </p>
    </div>
  <% if customer.image.present?  %>
    <div id="img">
      <%= image_tag(customer.image) %>
    </div>
  <% end  %>

    <footer class="foot" >
     <p> <strong >Phone: </strong>
        <%= customer.phone_number %>
      </p>

      <p>
      <strong>Email: </strong>
        <%= customer.email %>
      </p>
      <p>
      <strong>Notes:</strong>
         <br ><%= customer.notes %>
        </p>
    </footer>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<div class="tit">
<h4 class="title is-3">Alphabetized Customers</h4>
</div>

<div><%= link_to "All Customers", root_path%>  | <%= link_to "Customers Missing Email", missing_email_customers_path %></div>
<div class="columns is-multiline ">
  <%= render partial: 'customer',
             collection: @customers %>
</div>

app/views/customers/index.html.erb
<div class="tit">
<h4 class="title is-3">All Customers</h4>
</div>

<div><%= link_to "Alphabetized", alphabetized_customers_path %> | <%= link_to "Customers Missing Email",missing_email_customers_path %></div>
<div class="columns is-multiline ">
  <%= render partial: 'customer',
             collection: @customers %>
</div>

app/views/customers/missing_email.html.erb
<div class="tit">
<h4 class="title is-3">Customers Missing Emails</h4>
</div>

<div><%= link_to "All Customers", root_path%>  | <%= link_to "Alphabetized Customers", alphabetized_customers_path%></div>
<div class="columns is-multiline ">
  <%= render partial: 'customer',
             collection: @customers %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerRelationManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

  </head>

  <body>
<section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
  </body>
</html>